remote_theme: hydecorp/hydejack@v9.1.6
url: https://www.zanetdev.com
baseurl: ''
github:
  is_project_page: false
plugins:
  - jekyll-include-cache
menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/
  - title: "@microsoft.com"
    url:   https://microsoft.com/
